require("mustafabalila.plugins-setup")

require("mustafabalila.core.options")
require("mustafabalila.core.colorscheme")
require("mustafabalila.core.keymaps")

require("mustafabalila.plugins.nvim-tree")
require("mustafabalila.plugins.comment")
require("mustafabalila.plugins.lualine")
require("mustafabalila.plugins.telescope")
require("mustafabalila.plugins.nvim-cmp")
require("mustafabalila.plugins.gitsigns")
require("mustafabalila.plugins.autopairs")
require("mustafabalila.plugins.treesitter")
require("mustafabalila.plugins.lsp.mason")
require("mustafabalila.plugins.lsp.lspsaga")
require("mustafabalila.plugins.lsp.null-ls")
require("mustafabalila.plugins.lsp.lspconfig")
